src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Driver_Id__c</fullName>
        <description>Driver id from Tenstreet.</description>
        <label>Driver Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Marketing_Grade__c</fullName>
        <description>Marketing grade.</description>
        <label>Marketing Grade</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Score__c</fullName>
        <description>Marketing Score field from Tenstreet.</description>
        <label>Marketing Score</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_App_Source__c</fullName>
        <description>App source from Tenstreet.</description>
        <label>TS App Source</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_Declined_Reason__c</fullName>
        <description>Declined reason from Tenstreet.</description>
        <label>TS Declined Reason</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_Disqualified_Reason__c</fullName>
        <description>Disqualified reason from Tenstreet.</description>
        <label>TS Disqualified Reason</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_Division__c</fullName>
        <description>Division field from Tenstreet.</description>
        <label>TS Division</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_Experience__c</fullName>
        <description>Experience field from Tenstreet.</description>
        <label>TS Experience</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_First_Activity__c</fullName>
        <description>First Activity field from Tenstreet.</description>
        <label>TS First Activity</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_Fleet__c</fullName>
        <description>Fleet field from Tenstreet.</description>
        <label>TS Fleet</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_Last_Activity__c</fullName>
        <description>Last Activity field from Tenstreet.</description>
        <label>TS Last Activity</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_Last_App_Date__c</fullName>
        <description>Last Application Date field from Tenstreet.</description>
        <label>TS Last App Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TS_Marketing_List__c</fullName>
        <description>Marketing list field from Tenstreet.</description>
        <label>TS Marketing List</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_Rehire_Eligible__c</fullName>
        <description>Rehire eligible field from Tenstreet.</description>
        <label>TS Rehire Eligible</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_Source__c</fullName>
        <description>Source field from Tenstreet.</description>
        <label>TS Source</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_Status__c</fullName>
        <description>Statue field from Tenstreet.</description>
        <label>TS Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Text Opt Out flag from Tenstreet.</description>
        <label>Text Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TenstreetListener.cls
@RestResource(urlMapping='/listener/*')
global with sharing class TenstreetListener {

    static final String ACCEPTED_FLAG = 'ACCEPTED';
    static final String REJECTED_FLAG = 'REJECTED';



    @HttpPost
    global static void parseTenstreetXML() {
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;

        String responseDesc = '';
        TenstreetListenerData data;
        String flag = ACCEPTED_FLAG;

        try{
            data = TenstreetListenerData.parseTenstreetData(req.requestBody.toString());

            List<Contact> matchingContacts = [Select Id, FirstName, LastName, Email,
                                            MailingStreet, MailingPostalCode,
                                            MailingCity, Phone from Contact 
                                        where Email =: data.personalData.contactData.InternetEmailAddress];
            if (matchingContacts.size() == 0){
                //create contact
                Contact con = new Contact();
                setContactFields(con, data);
                insert con;
                responseDesc = 'New record created.';

            }else{

                setContactFields(matchingContacts[0], data);
                update matchingContacts[0];
                responseDesc = 'Existing record updated';
                flag = REJECTED_FLAG;
            }
        }catch(Exception e){
            responseDesc = e.getMessage();
        }
        res.responseBody = Blob.valueOf(generateResponse(flag, responseDesc, data.driverId));
    }


    private static String generateResponse(String flag, String description, String employeeNumber){

        return '<?xml version="1.0" encoding="UTF-8"?>' +
                            '<TenstreetResponse>'+
                            '<EmployeeNumber>'+employeeNumber+'</EmployeeNumber>'+
                            '<Status>'+flag+'</Status>'+
                            '<Description>'+description+'</Description>'+
                            '</TenstreetResponse>';

    }

    private static void setContactFields(Contact con, TenstreetListenerData data){
        con.FirstName = data.personalData.personName.givenName;
        con.LastName = data.personalData.personName.familyName;
        con.Email = data.personalData.contactData.internetEmailAddress;
        con.MailingStreet = data.personalData.postalAddress.address1;
        con.MailingStreet += '\n' + data.personalData.postalAddress.address2;
        con.MailingCity = data.personalData.postalAddress.municipality;
        con.MailingPostalCode = data.personalData.postalAddress.postalCode;
        con.MailingState = data.personalData.postalAddress.region;
        con.Driver_Id__c = Integer.valueOf(data.driverId);
        con.Phone = data.personalData.contactData.primaryPhone;
        con.OtherPhone = data.personalData.contactData.secondaryPhone;
        con.HasOptedOutOfEmail = !(data.personalData.communicationPreferences.emailOptIn);
        con.Text_Opt_Out__c = !(data.personalData.communicationPreferences.textOptIn);
        con.TS_Status__c = data.applicationData.status;
        con.TS_App_Source__c = data.applicationData.appSource;
        con.TS_Last_App_Date__c = DateTime.parse(data.applicationData.lastApplicationDate);
        con.Marketing_Score__c = data.applicationData.customDataElements.customDataElementsMap.get('marketingScore').customDataValue;
        con.Marketing_Grade__c = data.applicationData.customDataElements.customDataElementsMap.get('marketingGrade').customDataValue;
        con.TS_Experience__c = data.applicationData.customDataElements.customDataElementsMap.get('experience').customDataValue;
        con.TS_Division__c = data.applicationData.customDataElements.customDataElementsMap.get('division').customDataValue;
        con.TS_Disqualified_Reason__c = data.applicationData.customDataElements.customDataElementsMap.get('disqualifiedReason').customDataValue;
        con.TS_Declined_Reason__c = data.applicationData.customDataElements.customDataElementsMap.get('declinedReason').customDataValue;
        con.TS_First_Activity__c = data.applicationData.customDataElements.customDataElementsMap.get('marketingFirstActivity').customDataValue;
        con.TS_Last_Activity__c = data.applicationData.customDataElements.customDataElementsMap.get('marketingLastActivity').customDataValue;
        con.TS_Fleet__c = data.applicationData.customDataElements.customDataElementsMap.get('fleet').customDataValue;
        con.TS_Rehire_Eligible__c = data.applicationData.customDataElements.customDataElementsMap.get('rehireEligible').customDataValue;
        con.TS_Source__c = data.applicationData.customDataElements.customDataElementsMap.get('applicationReferrerCode').customDataValue;
        con.TS_Marketing_List__c = data.applicationData.customDataElements.customDataElementsMap.get('marketingList').customDataValue;

    }
    
}